steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/jlopez-370123/prismacloud-demo/ccs-demo-image:${{ github.sha }}', '.']
# Prisma Cloud Scan
- name: 'Prisma Cloud Image Scan'
  id: scan
  uses: PaloAltoNetworks/prisma-cloud-scan@v1
  with:
    pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
    pcc_user: ${{ secrets.PCC_USER }}
    pcc_pass: ${{ secrets.PCC_PASS }}
    image_name: gcr.io/${{ secrets.GKE_PROJECT }}/${{ secrets.IMAGE }}:${{ github.sha }}
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/jlopez-370123/prismacloud-demo/ccs-demo-image:${{ github.sha }}']
