steps:
#Build the Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest', '.']

#Call the twistcli.sh script passing the image built in the previous step as a PARAMETER
#all the variables are passed to the Container in the ENV: section
- name: 'us-east1-docker.pkg.dev/jlopez-370123/twistcli/twistcli:latest'
  args: ['/twistcli.sh', 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest']
  env: 
  - 'PCC_CONSOLE_URL=${_PCC_CONSOLE_URL}'
  - 'PCC_USER=${_PCC_USER}'
  - 'PCC_PASS=${_PCC_PASS}'
  
#Push Image to the Google Artifactory Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest']

#In case the image is pushed to the registry it is displayed in the Pipeline log.
images:
- 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest'
