steps:
#Build the Image
#We are using a ubuntu image tagged as ubuntu:latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest', '.']

#Call the twistcli.sh script passing the image built in the previous step as a PARAMETER
#all the variables are passed to the Container in the ENV: section
- name: 'us-east1-docker.pkg.dev/jlopez-370123/twistcli'
  args: ['/twistcli.sh', 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest']
  env:
  - 'PCC_CONSOLE_URL=${{ secrets.PCC_CONSOLE_URL }}'
  - 'PCC_USER=${{ secrets.PCC_USER }}'
  - 'PCC_PASS=${{ secrets.PCC_PASS }}'

#If the PRISMA SCAN verdict is continue the Image is pushed to the Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest']

#In case the image is pushed to the registry it is displayed in the Pipeline log.
images:
- 'us-east1-docker.pkg.dev/jlopez-370123/gcp-prismacloud-demo/gcp-pc-image:latest'
